Implement expand/collaspe all button for publication page.
sfc-aqua/sfc-aqua.github.io pull request #248
Opened 2024-01-25 12:56 UTC by PorametPat

Add a simple button to toggle between expand and collapse all contents within publication page.

2024-01-31 03:57 UTC, zigen requested changes

2024-01-31 03:57 UTC, zigen commented on src/app/publications/page.tsx
> +        B
typo or something? could you remove it?

2024-04-10 00:41 UTC, zigen commented
@PorametPat ping

2024-05-04 03:42 UTC, PorametPat commented on src/app/publications/page.tsx
> +        B
I think it is typo.

2024-05-13 13:40 UTC, PorametPat commented
@zigen Ping

2024-05-13 13:50 UTC, zigen approved these changes

2024-05-17 06:07 UTC, merged