Amin update
sfc-aqua/sfc-aqua.github.io pull request #70
Opened 2023-09-26 12:28 UTC by hhatpsi

2023-09-26 14:06 UTC, rdviii requested changes
Let's do: rdv, kusumoto, other faculty, D, M, B, in that order.
So move Amin below me.

2023-09-27 10:11 UTC, rdviii approved these changes
Looks fine to me, but still failing some check?

2023-09-27 10:12 UTC, rdviii reviewed
You need to run lint to fix the formatting.

2023-09-27 13:42 UTC, PorametPat approved these changes

2023-09-27 13:42 UTC, merged